### ISSUE TITLE
References non-existent repo

### ISSUE THREAD

**Issue by aac-78** [DarK404/UR_Isaac-sim#3]
The readme mentions https://github.com/DarK404/moveit2_tutorials. I can’t find this tutorial.

**Comment by DarK404** [comment]
The link should be working fine, I just created a isaac_moveit_ur.py in the fork which is similar to the isaac_moveit.py
file in the [official tutorial](https://moveit.picknik.ai/main/doc/how_to_guides/isaac_panda/isaac_panda_tutorial.html).
