### ISSUE TITLE
docker compose  build

### ISSUE THREAD

**Issue by why371323** [DarK404/UR_Isaac-sim#4]
Hi,I encountered the following error. I hope to get your reply. Thank you very much.
> # Warning: running 'rosdep update' as root is not recommended.                                         
 => => #   You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.        
 => => # ERROR: unable to process source [https://raw.githubusercontent.com/moveit/moveit2_packages/jammy-humb
 => => # le/local.yaml]:                                                                                      
 => => # <urlopen error [Errno 101] Network is unreachable> (https://raw.githubusercontent.com/moveit/moveit2_
 => => # packages/jammy-humble/local.yaml)   
![截图 2024-09-11 23-27-35](https://github.com/user-attachments/assets/3b584b01-4dfe-4989-acfd-6515e94fb28e)

**Comment by why371323** [comment]
![截图 2024-09-11 23-33-45](https://github.com/user-attachments/assets/ab130357-e138-45ed-932f-362d33156f91)

**Comment by DarK404** [comment]
It looks like a network issue inside the Docker container during the build. Try building the Docker image with the host network:
 `docker compose build --network=host`
If that doesn't work, try rebuilding without cache:
 `docker compose build --no-cache`
Hope this helps!
